#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>
using namespace std;

struct Edge { int u,v,length,cost,capacity,currentLoad; };
vector<string> nodeName={"","Engineering Building","YKSG-2","RASG-1","Food Court","Auditorium","AB-4","Annex Building","Admission Building","Hall Accommodation","ID Card Section","Gate-4","Gate-3","Gate-2","AB-1","Teachers Home","Gate-8","Mosque","AB-3","Green Garden","Gate-1","Transport Building"};
vector<Edge> edges={
{6,7,120,12000,100,25},{6,5,80,8000,100,45},{5,4,60,6000,100,60},{4,3,90,9000,100,30},{3,2,70,7000,100,70},{2,1,100,10000,100,80},
{3,14,110,11000,100,35},{6,14,75,7500,100,20},{6,11,50,5000,100,75},{6,8,95,9500,100,40},
{9,8,65,6500,100,25},{9,12,85,8500,100,55},{8,12,55,5500,100,65},{8,10,45,4500,100,30},{10,13,70,7000,100,50},
{14,15,90,9000,100,45},{15,16,60,6000,100,70},{14,17,50,5000,100,35},{17,18,65,6500,100,50},{18,3,80,8000,100,25},{3,19,75,7500,100,40},{3,20,100,10000,100,65},{14,21,120,12000,100,30}};
string username="Name", password="1234";
int findNode(const string& s){ for(int i=1;i<(int)nodeName.size();++i) if(nodeName[i]==s) return i; return -1; }
int edgeBetween(int a,int b,int skip=-1){ for(int i=0;i<(int)edges.size();++i) if(i!=skip && ((edges[i].u==a&&edges[i].v==b)||(edges[i].u==b&&edges[i].v==a))) return i; return -1; }

struct PathResult { bool ok=false; vector<int> path; int length=0,cost=0; };
PathResult dijkstra(int s,int t,int skip=-1,bool capacityFilter=false,int bw=0){
 int n=nodeName.size()-1, INF=1e9; vector<int>d(n+1,INF),p(n+1,-1); vector<char>vis(n+1); d[s]=0;
 for(int k=0;k<n;k++){int u=-1; for(int i=1;i<=n;i++) if(!vis[i]&&d[i]<INF&&(u==-1||d[i]<d[u]))u=i; if(u==-1)break;vis[u]=1; for(int i=0;i<(int)edges.size();i++){if(i==skip)continue; auto&e=edges[i]; int v=-1;if(e.u==u)v=e.v;else if(e.v==u)v=e.u;if(v<0)continue;if(capacityFilter&&e.capacity-e.currentLoad<bw)continue;if(d[u]+e.length<d[v]){d[v]=d[u]+e.length;p[v]=u;}}}
 if(d[t]==INF)return {}; PathResult r;r.ok=true;r.length=d[t];for(int x=t;x!=-1;x=p[x])r.path.push_back(x);reverse(r.path.begin(),r.path.end());for(size_t i=1;i<r.path.size();i++){int ei=edgeBetween(r.path[i-1],r.path[i],skip);if(ei>=0)r.cost+=edges[ei].cost;}return r;
}
int shortestDistance(int s,int t){auto r=dijkstra(s,t);return r.ok?r.length:-1;}

string esc(const string&s){string o;for(char c:s){if(c=='\\')o+="\\\\";else if(c=='\"')o+="\\\"";else if(c=='\n')o+="\\n";else if(c=='\r')o+="\\r";else o+=c;}return o;}
string jsonQuote(const string&s){return "\""+esc(s)+"\"";}
string pathJson(const vector<int>&p){ostringstream o;o<<"[";for(size_t i=0;i<p.size();i++){if(i)o<<",";o<<jsonQuote(nodeName[p[i]]);}o<<"]";return o.str();}
string edgeJson(int i){auto&e=edges[i];ostringstream o;o<<"{\"id\":"<<i<<",\"source\":"<<e.u<<",\"target\":"<<e.v<<",\"sourceName\":"<<jsonQuote(nodeName[e.u])<<",\"targetName\":"<<jsonQuote(nodeName[e.v])<<",\"length\":"<<e.length<<",\"cost\":"<<e.cost<<",\"capacity\":"<<e.capacity<<",\"currentLoad\":"<<e.currentLoad<<",\"available\":"<<e.capacity-e.currentLoad<<"}";return o.str();}
string networkJson(){ostringstream o;o<<"{\"nodes\":[";for(int i=1;i<(int)nodeName.size();i++){if(i>1)o<<",";o<<"{\"id\":"<<i<<",\"name\":"<<jsonQuote(nodeName[i])<<"}";}o<<"],\"edges\":[";for(int i=0;i<(int)edges.size();i++){if(i)o<<",";o<<edgeJson(i);}o<<"]}";return o.str();}
string trim(string s){while(!s.empty()&&isspace((unsigned char)s.back()))s.pop_back();size_t p=0;while(p<s.size()&&isspace((unsigned char)s[p]))p++;return s.substr(p);}
string jsonString(const string&body,const string&key){string pat="\""+key+"\"";size_t p=body.find(pat);if(p==string::npos)return"";p=body.find(':',p+pat.size());if(p==string::npos)return"";p++;while(p<body.size()&&isspace((unsigned char)body[p]))p++;if(p>=body.size()||body[p]!='\"')return"";p++;string o;bool escp=false;for(;p<body.size();p++){char c=body[p];if(escp){o+=c;escp=false;}else if(c=='\\')escp=true;else if(c=='\"')break;else o+=c;}return o;}
int jsonInt(const string&body,const string&key,int def=0){string pat="\""+key+"\"";size_t p=body.find(pat);if(p==string::npos)return def;p=body.find(':',p+pat.size());if(p==string::npos)return def;p++;while(p<body.size()&&isspace((unsigned char)body[p]))p++;return atoi(body.c_str()+p);}
vector<int> jsonIntArray(const string&body,const string&key){vector<int>r;string pat="\""+key+"\"";size_t p=body.find(pat);if(p==string::npos)return r;p=body.find('[',p+pat.size());size_t e=body.find(']',p);if(p==string::npos||e==string::npos)return r;string s=body.substr(p+1,e-p-1);stringstream ss(s);string x;while(getline(ss,x,','))r.push_back(atoi(trim(x).c_str()));return r;}
string errorJson(const string&m){return "{\"ok\":false,\"error\":"+jsonQuote(m)+"}";}

string cableSearch(const string&name){int n=findNode(name);if(n<0)return errorJson("Building not found");ostringstream o;o<<"{\"ok\":true,\"building\":"<<jsonQuote(name)<<",\"results\":[";bool first=true;for(int i=0;i<(int)edges.size();i++)if(edges[i].u==n||edges[i].v==n){if(!first)o<<",";first=false;o<<edgeJson(i);}o<<"]}";return o.str();}
string shortestApi(const string&a,const string&b){int s=findNode(a),t=findNode(b);if(s<0)return errorJson("Starting point not found");if(t<0)return errorJson("Ending point not found");auto r=dijkstra(s,t);if(!r.ok)return errorJson("No route available");ostringstream o;o<<"{\"ok\":true,\"path\":"<<pathJson(r.path)<<",\"totalLength\":"<<r.length<<",\"totalCost\":"<<r.cost<<"}";return o.str();}
int compSize(int start,int skip){vector<char>v(nodeName.size());vector<int>q{start};v[start]=1;for(size_t h=0;h<q.size();h++){int u=q[h];for(int i=0;i<(int)edges.size();i++){if(i==skip)continue;int z=-1;if(edges[i].u==u)z=edges[i].v;else if(edges[i].v==u)z=edges[i].u;if(z>0&&!v[z]){v[z]=1;q.push_back(z);}}}return q.size();}
string failureApi(int idx){if(idx<0||idx>=(int)edges.size())return errorJson("Invalid cable");auto&e=edges[idx];int a=compSize(e.u,idx),b=compSize(e.v,idx),n=nodeName.size()-1;string status;if(a==n&&b==n)status="SAFE";else if(a==1||b==1)status="WARNING";else status="CRITICAL";auto backup=dijkstra(e.u,e.v,idx);ostringstream o;o<<"{\"ok\":true,\"status\":"<<jsonQuote(status)<<",\"failedEdge\":"<<edgeJson(idx)<<",\"componentA\":"<<a<<",\"componentB\":"<<b<<",\"backupFound\":"<<(backup.ok?"true":"false");if(backup.ok)o<<",\"backupPath\":"<<pathJson(backup.path)<<",\"backupLength\":"<<backup.length<<",\"backupCost\":"<<backup.cost;o<<"}";return o.str();}
string technicianApi(const vector<int>&tech,const vector<int>&fault){if(tech.empty()||fault.empty())return errorJson("Add at least one technician and one fault");vector<vector<int>>m(tech.size(),vector<int>(fault.size()));for(size_t i=0;i<tech.size();i++)for(size_t j=0;j<fault.size();j++)m[i][j]=shortestDistance(tech[i],fault[j]);vector<char>tu(tech.size()),fa(fault.size());vector<int>af(tech.size(),-1),ad(tech.size());int total=0;for(size_t k=0;k<min(tech.size(),fault.size());k++){int bi=-1,bj=-1,bd=INT_MAX;for(size_t i=0;i<tech.size();i++)if(!tu[i])for(size_t j=0;j<fault.size();j++)if(!fa[j]&&m[i][j]>=0&&m[i][j]<bd){bd=m[i][j];bi=i;bj=j;}if(bi<0)break;tu[bi]=1;fa[bj]=1;af[bi]=bj;ad[bi]=bd;total+=bd;}ostringstream o;o<<"{\"ok\":true,\"matrix\":[";for(size_t i=0;i<m.size();i++){if(i)o<<",";o<<"[";for(size_t j=0;j<m[i].size();j++){if(j)o<<",";o<<m[i][j];}o<<"]";}o<<"],\"assignments\":[";bool first=true;for(size_t i=0;i<tech.size();i++){if(!first)o<<",";first=false;o<<"{\"technician\":"<<jsonQuote("Technician-"+to_string(i+1))<<",\"location\":"<<jsonQuote(nodeName[tech[i]])<<",\"fault\":"<<(af[i]>=0?jsonQuote("Fault-"+to_string(af[i]+1)):"null");if(af[i]>=0)o<<",\"faultLocation\":"<<jsonQuote(nodeName[fault[af[i]]])<<",\"distance\":"<<ad[i]<<",\"eta\":"<<fixed<<setprecision(2)<<ad[i]/100.0<<",\"status\":\"DISPATCHED\"";else o<<",\"status\":\"AVAILABLE\"";o<<"}";}o<<"],\"pending\":[";first=true;for(size_t j=0;j<fault.size();j++)if(!fa[j]){if(!first)o<<",";first=false;o<<"{\"fault\":"<<jsonQuote("Fault-"+to_string(j+1))<<",\"location\":"<<jsonQuote(nodeName[fault[j]])<<"}";}o<<"],\"totalDistance\":"<<total<<"}";return o.str();}
string trafficApi(const string&a,const string&b,int bw){int s=findNode(a),t=findNode(b);if(s<0||t<0)return errorJson("Invalid source or destination");if(bw<=0)return errorJson("Invalid bandwidth");auto normal=dijkstra(s,t);auto aware=dijkstra(s,t,-1,true,bw);ostringstream o;o<<"{\"ok\":true,\"requiredBandwidth\":"<<bw<<",\"normalFound\":"<<(normal.ok?"true":"false")<<",\"trafficFound\":"<<(aware.ok?"true":"false");if(normal.ok)o<<",\"normalPath\":"<<pathJson(normal.path)<<",\"normalLength\":"<<normal.length<<",\"normalCost\":"<<normal.cost;if(aware.ok)o<<",\"trafficPath\":"<<pathJson(aware.path)<<",\"trafficLength\":"<<aware.length<<",\"trafficCost\":"<<aware.cost; o<<"}";return o.str();}

string filePath(const string&path){if(path=="/")return"/public/index.html";if(path.rfind("/public/",0)==0)return path;return "/public"+path;}
string mime(const string&p){if(p.ends_with(".html"))return"text/html; charset=utf-8";if(p.ends_with(".css"))return"text/css";if(p.ends_with(".js"))return"application/javascript";if(p.ends_with(".svg"))return"image/svg+xml";return"text/plain";}
string handle(const string&method,const string&path,const string&body){if(method=="GET"&&path=="/api/network")return networkJson();if(method=="POST"&&path=="/api/login"){string u=jsonString(body,"username"),p=jsonString(body,"password");return string("{\"ok\":")+(u==username&&p==password?"true":"false")+",\"message\":"+jsonQuote(u==username&&p==password?"Login successful":"Invalid username or password")+"}";}if(method=="POST"&&path=="/api/cable-search")return cableSearch(jsonString(body,"name"));if(method=="POST"&&path=="/api/shortest-path")return shortestApi(jsonString(body,"source"),jsonString(body,"destination"));if(method=="POST"&&path=="/api/cable-failure")return failureApi(jsonInt(body,"edge"));if(method=="POST"&&path=="/api/technician-dispatch")return technicianApi(jsonIntArray(body,"technicians"),jsonIntArray(body,"faults"));if(method=="POST"&&path=="/api/traffic")return trafficApi(jsonString(body,"source"),jsonString(body,"destination"),jsonInt(body,"bandwidth"));if(method=="GET"&&path.rfind("/api/",0)==0)return errorJson("Unknown API endpoint");
 string fp=filePath(path);ifstream f("."+fp,ios::binary);if(!f)return "";stringstream ss;ss<<f.rdbuf();return ss.str();}
void sendResp(int c,int code,const string&type,const string&body){string msg=code==200?"OK":code==404?"Not Found":"Bad Request";ostringstream h;h<<"HTTP/1.1 "<<code<<" "<<msg<<"\r\nContent-Type: "<<type<<"\r\nContent-Length: "<<body.size()<<"\r\nAccess-Control-Allow-Origin: *\r\nConnection: close\r\n\r\n";string x=h.str()+body;send(c,x.data(),x.size(),0);}
int main(){int port=8080;if(const char*p=getenv("PORT"))port=atoi(p);int s=socket(AF_INET,SOCK_STREAM,0);int yes=1;setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));sockaddr_in addr{};addr.sin_family=AF_INET;addr.sin_addr.s_addr=INADDR_ANY;addr.sin_port=htons(port);if(bind(s,(sockaddr*)&addr,sizeof(addr))<0)return 1;if(listen(s,32)<0)return 1;cerr<<"Campus Cable Planner listening on "<<port<<"\n";while(true){int c=accept(s,nullptr,nullptr);if(c<0)continue;string req;char buf[8192];int n=recv(c,buf,sizeof(buf),0);if(n<=0){close(c);continue;}req.assign(buf,n);size_t hEnd=req.find("\r\n\r\n");if(hEnd==string::npos){close(c);continue;}string head=req.substr(0,hEnd),body=req.substr(hEnd+4);istringstream hs(head);string method,path,ver;hs>>method>>path>>ver;size_t cl=head.find("Content-Length:");if(cl!=string::npos){size_t e=head.find("\r\n",cl);int len=atoi(head.substr(cl+15,e-cl-15).c_str());while((int)body.size()<len){n=recv(c,buf,sizeof(buf),0);if(n<=0)break;body.append(buf,n);}}string out=handle(method,path,body);if(out.empty())sendResp(c,404,"text/plain","Not found");else {bool api=path.rfind("/api/",0)==0;sendResp(c,200,api?"application/json; charset=utf-8":mime(path),out);}close(c);} }
